name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
      - 'global.json'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        runtime:
          - win-x64
          - win-arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Publish NitroWin
        run: >
          dotnet publish src/NitroWin/NitroWin.csproj
          --configuration Release
          --runtime ${{ matrix.runtime }}
          --output publish/NitroWin-${{ matrix.runtime }}

      - name: Upload NitroWin binaries
        uses: actions/upload-artifact@v7
        with:
          name: NitroWin-${{ matrix.runtime }}
          path: publish/NitroWin-${{ matrix.runtime }}

      - name: Publish NitroWin Control Panel
        run: >
          dotnet publish src/NitroWin.ControlPanel/NitroWin.ControlPanel
          --configuration Release
          --runtime ${{ matrix.runtime }}
          --output publish/NitroWin.ControlPanel-${{ matrix.runtime }}

      - name: Upload NitroWin Control Panel binaries
        uses: actions/upload-artifact@v7
        with:
          name: NitroWin.ControlPanel-${{ matrix.runtime }}
          path: publish/NitroWin.ControlPanel-${{ matrix.runtime }}
