name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "deployment/**"
      - ".github/workflows/build.yml"
      - "global.json"
      - "NitroWin.slnx"
      - "LICENSE"

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - runtime: win-x64
            architecture: x64
          - runtime: win-arm64
            architecture: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Publish NitroWin
        run: >
          dotnet publish src/NitroWin/NitroWin.csproj
          --configuration Release
          --runtime ${{ matrix.runtime }}
          -p:PublishSingleFile=true
          --self-contained
          --output publish/NitroWin-${{ matrix.runtime }}

      - name: Copy files from dist
        run: Copy-Item -Path ./dist/* -Destination publish/NitroWin-${{ matrix.runtime }} -Recurse -Force

      - name: Upload files
        uses: actions/upload-artifact@v7
        with:
          path: publish/NitroWin-${{ matrix.runtime }}

  build-installer:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - runtime: win-x64
            architecture: x64
          - runtime: win-arm64
            architecture: arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Publish NitroWin
        run: >
          dotnet publish src/NitroWin/NitroWin.csproj
          --configuration Release
          --runtime ${{ matrix.runtime }}
          --output publish/NitroWin-${{ matrix.runtime }}

      - name: Compile installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.9
        with:
          path: deployment/NitroWin.iss
          options: /DTargetArch=${{ matrix.architecture }}

      - name: Upload installer
        uses: actions/upload-artifact@v7
        with:
          path: deployment/Output/NitroWinSetup-${{ matrix.architecture }}.exe
          archive: false
